apiVersion: v1
kind: ConfigMap
metadata:
  namespace: openshift-service-ca-operator
  name: service-ca-operator-config
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
data:
  operator-config.yaml: |
    apiVersion: operator.openshift.io/v1alpha1
    kind: GenericOperatorConfig
