apiVersion: servicecertsigner.config.openshift.io/v1alpha1
kind: ServiceCertSignerOperatorConfig
metadata:
  name: instance
spec:
  managementState: Managed
  imagePullSpec: openshift/origin-service-ca:latest
  version: 3.10.0
  logging:
    level: 4
  replicas: 1