apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: openshift-service-ca
  name: service-ca
  labels:
    app: openshift-service-ca
    service-ca: "true"
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: openshift-service-ca
      service-ca: "true"
  template:
    metadata:
      name: service-ca
      labels:
        app: openshift-service-ca
        service-ca: "true"
    spec:
      serviceAccountName: service-ca-sa
      containers:
      - name: service-ca-controller
        image: ${IMAGE}
        imagePullPolicy: IfNotPresent
        command: ["service-ca", "serving-cert-signer"]
        args:
        - "--config=/var/run/configmaps/config/controller-config.yaml"
        ports:
        - containerPort: 8443
        volumeMounts:
        - mountPath: /var/run/configmaps/config
          name: config
        - mountPath: /var/run/secrets/signing-key
          name: signing-key
        - mountPath: /var/run/secrets/serving-cert
          name: serving-cert
      volumes:
      - name: serving-cert
        secret:
          secretName: service-ca-serving-cert
          optional: true
      - name: signing-key
        secret:
          secretName: service-ca-signing-key
      - name: config
        configMap:
          name: service-ca-config



