apiVersion: v1
kind: Service
metadata:
  namespace: openshift-service-ca
  name: service-ca
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: service-ca-serving-cert
    prometheus.io/scrape: "true"
    prometheus.io/scheme: https
spec:
  selector:
    service-ca: "true"
  ports:
  - name: https
    port: 443
    targetPort: 8443
